FROM python:3.12-slim

RUN mkdir /app
RUN mkdir /config
RUN mkdir /assets
WORKDIR /app

COPY requirements-web.txt .
RUN pip install -r requirements-web.txt

COPY . .
COPY web.env .

COPY hw2-config/assets /assets

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "pygrader-web.py", "--server.port=8501", "--server.address=0.0.0.0"]
