FROM python:3.13-slim

RUN mkdir /app
RUN mkdir /project
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "pygrader-web.py", "--server.port=8501", "--server.address=0.0.0.0"]
