[project]
name = "pygrader"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "py-cove @ git+https://github.com/lyubolp/py-cove.git",
    "pylint>=4.0.8",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "types-requests>=2.33.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
# List only the directory/package you want to include
packages = ["grader", "grader.checks", "grader.utils", "grader.models", "config"]

[tool.setuptools.package-data]
config = ["grader_requirements.txt", "mypy_type_hints_2024.ini", "2024.pylintrc"]

[tool.complexipy]
paths = ["grader", "tests", "desktop", "web"]
max-complexity-allowed = 15
quiet = false
sort = "asc"
details = "low"

[tool.complexipy.output]
json = true

[tool.uv.sources]
py-cove = { git = "https://github.com/lyubolp/py-cove", rev = "v1.4.0" }

[dependency-groups]
dev = [
    "complexipy>=8.0.0",
    "coverage>=7.16.0",
    "mypy>=2.3.1",
    "myst-parser>=5.1.0",
    "ruff>=0.16.6",
    "sphinx>=9.1.0",
    "sphinx-autodoc2>=0.4.2",
    "sphinx-rtd-theme>=3.1.0",
    "sphinx-rtd-theme-ext-color-contrast>=0.3.2",
]
grader-runtime = [
    "coverage>=7.16.0",
    "mypy>=2.3.1",
    "psutil>=7.2.2",
    "pylint>=4.0.8",
    "pytest>=9.1.1",
    "requests>=2.34.2",
]
